--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: conversionfactor
    version: v1
  name: conversionfactor
spec: 
  strategy: # Default, so usually not specified
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: conversionfactor
      version: v1
  template: 
    metadata: 
      labels: 
        app: conversionfactor
        version: v1

    spec: 

      containers: 
        - 
          image: "prashantadockertest/conversionfactor:1"
          imagePullPolicy: Always
          name: conversionfactor
          ports: 
#          - containerPort: 8081   
          - name: httpport
            containerPort: 8081
            hostPort: 8081      
          env:
            - name: conversionfactor.configserverurl
              value: "http://configserver:8888"
            - name: conversionfactor.eureka.url
              value: "http://eureka:8761/eureka"  

              
                    