spring:
  cloud:
    config:
      server:
        git:
         #uri: C:\gitlocal
         uri: https://github.com/prashanta1984/Microservice.git
         skipSslValidation: true
    

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: '*'